/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PastImport } from './routes/past'
import { Route as OrderImport } from './routes/Order'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ContactLazyImport = createFileRoute('/contact')()

// Create/Update Routes

const ContactLazyRoute = ContactLazyImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))

const PastRoute = PastImport.update({
  path: '/past',
  getParentRoute: () => rootRoute,
} as any)

const OrderRoute = OrderImport.update({
  path: '/Order',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Order': {
      id: '/Order'
      path: '/Order'
      fullPath: '/Order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
    '/past': {
      id: '/past'
      path: '/past'
      fullPath: '/past'
      preLoaderRoute: typeof PastImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Order': typeof OrderRoute
  '/past': typeof PastRoute
  '/contact': typeof ContactLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Order': typeof OrderRoute
  '/past': typeof PastRoute
  '/contact': typeof ContactLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Order': typeof OrderRoute
  '/past': typeof PastRoute
  '/contact': typeof ContactLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Order' | '/past' | '/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Order' | '/past' | '/contact'
  id: '__root__' | '/' | '/Order' | '/past' | '/contact'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrderRoute: typeof OrderRoute
  PastRoute: typeof PastRoute
  ContactLazyRoute: typeof ContactLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrderRoute: OrderRoute,
  PastRoute: PastRoute,
  ContactLazyRoute: ContactLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/Order",
        "/past",
        "/contact"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/Order": {
      "filePath": "Order.jsx"
    },
    "/past": {
      "filePath": "past.jsx"
    },
    "/contact": {
      "filePath": "contact.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
